server:
  port: 80

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000   # hystrix 超时时间
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'