spring:
  rabbitmq:
    host: 10.0.0.121
    port: 5672
    username: admin
    password: cex
    virtual-host: lucifer
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 5000

  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-mq-rabbit?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lucifer
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      max-active: 20


logging:
  level:
    root: info
    com.beyond: debug