spring:
  rabbitmq:
    host: 10.0.0.121
    port: 5672
    username: admin
    password: cex
    virtual-host: lucifer
    listener:
      type: simple
      simple:
        default-requeue-rejected: true
        acknowledge-mode: manual
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 5000

logging:
  level:
    root: info
    com.beyond: debug