spring:
  rabbitmq:
    host: 10.0.0.121
    port: 5672
    username: admin
    password: cex
    virtual-host: lucifer
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        auto-startup: true
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 2
          max-interval: 20000
          stateless: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-mq-rabbit?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lucifer
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      max-active: 20


logging:
  level:
    root: info
    com.beyond: debug