server:
  port: 8002

spring:
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      # 指定默认消费者group id --> 由于在kafka中，同一组中的 consumer 不会读取到同一个消息，依靠 groud.id 设置组名
      group-id: test-group
      # smallest和largest才有效，如果smallest重新0开始读取，如果是largest从logfile的offset读取。一般情况下我们都是设置smallest
      auto-offset-reset: earliest
      enable-auto-commit: true
      #如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
      auto-commit-interval: 100

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
