package com.beyond.rabbitmq.entity;

public class MqMessageWithBLOBs extends MqMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message.message_properties
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    private String messageProperties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message.message_body
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    private String messageBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message.message_properties
     *
     * @return the value of mq_message.message_properties
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public String getMessageProperties() {
        return messageProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message.message_properties
     *
     * @param messageProperties the value for mq_message.message_properties
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public void setMessageProperties(String messageProperties) {
        this.messageProperties = messageProperties == null ? null : messageProperties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message.message_body
     *
     * @return the value of mq_message.message_body
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public String getMessageBody() {
        return messageBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message.message_body
     *
     * @param messageBody the value for mq_message.message_body
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody == null ? null : messageBody.trim();
    }
}