package com.beyond.rabbitmq.entity;

public class MqMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message.id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message.message_id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    private String messageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message.id
     *
     * @return the value of mq_message.id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message.id
     *
     * @param id the value for mq_message.id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message.message_id
     *
     * @return the value of mq_message.message_id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message.message_id
     *
     * @param messageId the value for mq_message.message_id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }
}