package com.beyond.rabbitmq.entity;

public class MqOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_order.id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_order.name
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_order.id
     *
     * @return the value of mq_order.id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_order.id
     *
     * @param id the value for mq_order.id
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_order.name
     *
     * @return the value of mq_order.name
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_order.name
     *
     * @param name the value for mq_order.name
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}