package com.beyond.rabbitmq.mapper;

import com.beyond.rabbitmq.entity.MqOrder;

public interface MqOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    int insert(MqOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    int insertSelective(MqOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    MqOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    int updateByPrimaryKeySelective(MqOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_order
     *
     * @mbg.generated Fri Aug 28 14:28:31 CST 2020
     */
    int updateByPrimaryKey(MqOrder record);
}