spring:
  dubbo:
    server: true
    application:
      id: @project.artifactId@
      name: @project.artifactId@
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20080
